import { useState, useEffect } from 'react';

function ConfidenceBadge({ level }) {
  const styles = {
    high:   'bg-emerald-900/40 text-emerald-400 border-emerald-700',
    medium: 'bg-amber-900/40  text-amber-400  border-amber-700',
    low:    'bg-slate-700     text-slate-400  border-slate-600',
  };
  return (
    <span className={`pill border text-xs ${styles[level] || styles.low}`}>
      {level} confidence
    </span>
  );
}

function Skeleton({ className = '' }) {
  return <div className={`animate-pulse bg-slate-700 rounded ${className}`} />;
}

export default function InsightReport({ niche }) {
  const [insight, setInsight] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const load = () => {
    setLoading(true);
    setError(null);

    fetch(`/api/insights/${niche}`)
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then(d => { setInsight(d); setLoading(false); })
      .catch(err => { setError(err.message); setLoading(false); });
  };

  useEffect(load, [niche]);

  return (
    <div>
      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="section-heading">AI Intelligence Report</h2>
          <p className="text-slate-500 text-sm mt-1">Generated by Claude · {niche} audience analysis</p>
        </div>
        <button
          onClick={load}
          disabled={loading}
          className="px-4 py-2 bg-slate-700 hover:bg-slate-600 disabled:opacity-40 text-sm rounded-lg transition-colors"
        >
          {loading ? 'Generating…' : 'Regenerate'}
        </button>
      </div>

      {error && (
        <div className="rounded-lg bg-red-900/30 border border-red-700 p-4 text-red-300 text-sm mb-6">
          {error}
        </div>
      )}

      {loading ? (
        <div className="space-y-4">
          <Skeleton className="h-9 w-2/3" />
          <Skeleton className="h-20 w-full" />
          <div className="grid grid-cols-2 gap-6 mt-6">
            <div className="space-y-3">
              <Skeleton className="h-5 w-32" />
              {Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-4 w-full" />)}
            </div>
            <div className="space-y-3">
              <Skeleton className="h-5 w-32" />
              {Array.from({ length: 2 }).map((_, i) => <Skeleton key={i} className="h-4 w-full" />)}
            </div>
          </div>
        </div>
      ) : insight && (
        <div className="bg-gradient-to-br from-slate-800 to-slate-800/60 border border-slate-700 rounded-xl p-8">
          <div className="flex items-start justify-between gap-4 mb-5">
            <h3 className="font-serif text-2xl font-semibold text-white leading-snug">{insight.title}</h3>
            <ConfidenceBadge level={insight.confidence} />
          </div>

          <p className="text-slate-300 leading-relaxed mb-8 border-l-2 border-brand-600 pl-4">
            {insight.summary}
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h4 className="text-slate-400 text-xs uppercase tracking-widest mb-3">Key Audience Behaviours</h4>
              <ul className="space-y-2">
                {(insight.keyBehaviors || []).map((b, i) => (
                  <li key={i} className="flex gap-2 text-sm text-slate-300">
                    <span className="text-brand-500 mt-0.5 flex-shrink-0">▸</span>
                    {b}
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="text-slate-400 text-xs uppercase tracking-widest mb-3">Marketing Angles</h4>
              <ul className="space-y-2">
                {(insight.marketingAngles || []).map((a, i) => (
                  <li key={i} className="flex gap-2 text-sm text-slate-300">
                    <span className="text-emerald-500 mt-0.5 flex-shrink-0">▸</span>
                    {a}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <p className="text-slate-600 text-xs mt-8 pt-4 border-t border-slate-700">
            Powered by Claude {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
        </div>
      )}
    </div>
  );
}
