/**
 * Empirika Demo Data
 * Rich, realistic fake data powering the dashboard in demo mode.
 * Niches are modelled on real FMCG / brand-relevant YouTube audience categories.
 */

export const AUDIENCE_DATA = {
  'Beauty & Skincare': [
    {
      channel_id: 'bty1',
      channel_name: 'Hyram',
      subscriber_count: 4100000,
      total_views: 28400000,
      total_watch_hours: 1420000,
      avg_view_duration_seconds: 924,
      total_subscribers_gained: 98400,
      total_likes: 1280000,
      total_comments: 214000,
      trend: [62, 68, 72, 76, 80, 84, 90],
      trend_pct: +28.4,
    },
    {
      channel_id: 'bty2',
      channel_name: 'Lisa Eldridge',
      subscriber_count: 2180000,
      total_views: 14200000,
      total_watch_hours: 710000,
      avg_view_duration_seconds: 1124,
      total_subscribers_gained: 48200,
      total_likes: 612000,
      total_comments: 98400,
      trend: [58, 62, 66, 68, 72, 76, 80],
      trend_pct: +19.2,
    },
    {
      channel_id: 'bty3',
      channel_name: 'Wayne Goss',
      subscriber_count: 3640000,
      total_views: 22100000,
      total_watch_hours: 1105000,
      avg_view_duration_seconds: 743,
      total_subscribers_gained: 74800,
      total_likes: 942000,
      total_comments: 162000,
      trend: [70, 74, 72, 78, 80, 82, 86],
      trend_pct: +22.7,
    },
    {
      channel_id: 'bty4',
      channel_name: 'Gothamista',
      subscriber_count: 980000,
      total_views: 6240000,
      total_watch_hours: 312000,
      avg_view_duration_seconds: 1084,
      total_subscribers_gained: 21400,
      total_likes: 284000,
      total_comments: 48200,
      trend: [48, 52, 54, 58, 56, 60, 64],
      trend_pct: +12.1,
    },
    {
      channel_id: 'bty5',
      channel_name: 'Skincare by Hyacinth',
      subscriber_count: 560000,
      total_views: 3480000,
      total_watch_hours: 174000,
      avg_view_duration_seconds: 864,
      total_subscribers_gained: 12800,
      total_likes: 148000,
      total_comments: 28400,
      trend: [40, 44, 46, 48, 50, 52, 56],
      trend_pct: +8.4,
    },
  ],

  'Health & Wellness': [
    {
      channel_id: 'hlw1',
      channel_name: 'Andrew Huberman',
      subscriber_count: 6800000,
      total_views: 48200000,
      total_watch_hours: 3856000,
      avg_view_duration_seconds: 4812,
      total_subscribers_gained: 184000,
      total_likes: 2140000,
      total_comments: 412000,
      trend: [74, 80, 84, 88, 86, 92, 96],
      trend_pct: +34.2,
    },
    {
      channel_id: 'hlw2',
      channel_name: 'Thomas DeLauer',
      subscriber_count: 3420000,
      total_views: 22800000,
      total_watch_hours: 1140000,
      avg_view_duration_seconds: 924,
      total_subscribers_gained: 68400,
      total_likes: 884000,
      total_comments: 148000,
      trend: [62, 68, 72, 74, 78, 80, 84],
      trend_pct: +21.4,
    },
    {
      channel_id: 'hlw3',
      channel_name: 'Yoga with Adriene',
      subscriber_count: 12400000,
      total_views: 84200000,
      total_watch_hours: 4210000,
      avg_view_duration_seconds: 1842,
      total_subscribers_gained: 284000,
      total_likes: 3120000,
      total_comments: 542000,
      trend: [78, 82, 80, 86, 88, 90, 94],
      trend_pct: +26.8,
    },
    {
      channel_id: 'hlw4',
      channel_name: 'Dr. Eric Berg',
      subscriber_count: 9200000,
      total_views: 62400000,
      total_watch_hours: 3120000,
      avg_view_duration_seconds: 784,
      total_subscribers_gained: 212000,
      total_likes: 2280000,
      total_comments: 384000,
      trend: [68, 72, 74, 78, 80, 84, 88],
      trend_pct: +24.1,
    },
  ],

  'Home & Living': [
    {
      channel_id: 'hom1',
      channel_name: 'Studio McGee',
      subscriber_count: 1840000,
      total_views: 11200000,
      total_watch_hours: 560000,
      avg_view_duration_seconds: 1124,
      total_subscribers_gained: 42800,
      total_likes: 484000,
      total_comments: 84200,
      trend: [56, 60, 64, 68, 70, 74, 78],
      trend_pct: +16.4,
    },
    {
      channel_id: 'hom2',
      channel_name: 'Mr. Kate',
      subscriber_count: 2640000,
      total_views: 16800000,
      total_watch_hours: 840000,
      avg_view_duration_seconds: 1384,
      total_subscribers_gained: 58400,
      total_likes: 712000,
      total_comments: 128000,
      trend: [64, 68, 66, 72, 74, 78, 82],
      trend_pct: +18.9,
    },
    {
      channel_id: 'hom3',
      channel_name: 'The Sorry Girls',
      subscriber_count: 1280000,
      total_views: 7840000,
      total_watch_hours: 392000,
      avg_view_duration_seconds: 1542,
      total_subscribers_gained: 28400,
      total_likes: 324000,
      total_comments: 58200,
      trend: [50, 54, 52, 58, 60, 64, 68],
      trend_pct: +14.2,
    },
    {
      channel_id: 'hom4',
      channel_name: 'Architectural Digest',
      subscriber_count: 3840000,
      total_views: 24200000,
      total_watch_hours: 1210000,
      avg_view_duration_seconds: 984,
      total_subscribers_gained: 84200,
      total_likes: 948000,
      total_comments: 164000,
      trend: [72, 76, 74, 80, 82, 86, 90],
      trend_pct: +22.8,
    },
    {
      channel_id: 'hom5',
      channel_name: 'IKEA Ideas',
      subscriber_count: 680000,
      total_views: 4240000,
      total_watch_hours: 212000,
      avg_view_duration_seconds: 724,
      total_subscribers_gained: 16800,
      total_likes: 182000,
      total_comments: 32400,
      trend: [44, 46, 48, 50, 52, 54, 56],
      trend_pct: +6.8,
    },
  ],

  'Food & Beverage': [
    {
      channel_id: 'fod1',
      channel_name: 'Joshua Weissman',
      subscriber_count: 9400000,
      total_views: 64200000,
      total_watch_hours: 3210000,
      avg_view_duration_seconds: 1184,
      total_subscribers_gained: 248000,
      total_likes: 2640000,
      total_comments: 482000,
      trend: [76, 80, 84, 88, 86, 92, 96],
      trend_pct: +32.4,
    },
    {
      channel_id: 'fod2',
      channel_name: 'Babish Culinary Universe',
      subscriber_count: 10200000,
      total_views: 72400000,
      total_watch_hours: 3620000,
      avg_view_duration_seconds: 984,
      total_subscribers_gained: 284000,
      total_likes: 2980000,
      total_comments: 528000,
      trend: [80, 84, 82, 88, 90, 94, 98],
      trend_pct: +36.8,
    },
    {
      channel_id: 'fod3',
      channel_name: 'Ethan Chlebowski',
      subscriber_count: 1840000,
      total_views: 12400000,
      total_watch_hours: 620000,
      avg_view_duration_seconds: 1084,
      total_subscribers_gained: 48200,
      total_likes: 524000,
      total_comments: 98400,
      trend: [58, 62, 66, 70, 72, 76, 80],
      trend_pct: +21.2,
    },
    {
      channel_id: 'fod4',
      channel_name: 'Pro Home Cooks',
      subscriber_count: 1240000,
      total_views: 8200000,
      total_watch_hours: 410000,
      avg_view_duration_seconds: 924,
      total_subscribers_gained: 32800,
      total_likes: 348000,
      total_comments: 64200,
      trend: [52, 56, 54, 60, 62, 66, 70],
      trend_pct: +16.4,
    },
  ],

  'Parenting & Family': [
    {
      channel_id: 'par1',
      channel_name: 'Big Life Journal',
      subscriber_count: 820000,
      total_views: 4840000,
      total_watch_hours: 242000,
      avg_view_duration_seconds: 1084,
      total_subscribers_gained: 22400,
      total_likes: 198000,
      total_comments: 42800,
      trend: [48, 52, 56, 58, 62, 64, 68],
      trend_pct: +14.8,
    },
    {
      channel_id: 'par2',
      channel_name: 'Mark Rober',
      subscriber_count: 24800000,
      total_views: 184000000,
      total_watch_hours: 9200000,
      avg_view_duration_seconds: 1384,
      total_subscribers_gained: 684000,
      total_likes: 7840000,
      total_comments: 1280000,
      trend: [82, 86, 90, 94, 92, 96, 98],
      trend_pct: +42.1,
    },
    {
      channel_id: 'par3',
      channel_name: 'SciShow Kids',
      subscriber_count: 4200000,
      total_views: 28400000,
      total_watch_hours: 1420000,
      avg_view_duration_seconds: 542,
      total_subscribers_gained: 84200,
      total_likes: 984000,
      total_comments: 164000,
      trend: [62, 66, 64, 70, 72, 76, 80],
      trend_pct: +18.2,
    },
    {
      channel_id: 'par4',
      channel_name: 'The Holderness Family',
      subscriber_count: 1640000,
      total_views: 10800000,
      total_watch_hours: 540000,
      avg_view_duration_seconds: 742,
      total_subscribers_gained: 38400,
      total_likes: 448000,
      total_comments: 84200,
      trend: [54, 58, 60, 62, 64, 68, 72],
      trend_pct: +12.6,
    },
    {
      channel_id: 'par5',
      channel_name: 'Cosmic Kids Yoga',
      subscriber_count: 2840000,
      total_views: 18400000,
      total_watch_hours: 920000,
      avg_view_duration_seconds: 1842,
      total_subscribers_gained: 64200,
      total_likes: 782000,
      total_comments: 142000,
      trend: [64, 68, 72, 74, 78, 80, 84],
      trend_pct: +21.4,
    },
  ],
};

export const TOTAL_TRENDS = {
  'Beauty & Skincare': { views: +24.8, watchHours: +22.4, avgDuration: +6.2, subscribers: +31.4 },
  'Health & Wellness': { views: +34.2, watchHours: +38.6, avgDuration: +12.8, subscribers: +42.1 },
  'Home & Living':     { views: +18.4, watchHours: +16.8, avgDuration: +4.2, subscribers: +22.6 },
  'Food & Beverage':   { views: +38.4, watchHours: +36.2, avgDuration: +8.4, subscribers: +46.8 },
  'Parenting & Family':{ views: +28.4, watchHours: +26.8, avgDuration: +9.6, subscribers: +34.2 },
};

export const AFFINITY_DATA = {
  'Beauty & Skincare': [
    {
      category: 'Fashion & Luxury Goods',
      engagement_pct: 78,
      description: 'High overlap with fashion hauls, luxury brand unboxing, and designer content consumers.',
      examples: ['Inthefrow', 'Bestdressed', 'Madeleine Olivia'],
    },
    {
      category: 'Health & Wellness',
      engagement_pct: 72,
      description: 'Strong crossover with clean beauty, holistic wellness, and ingredient-conscious content.',
      examples: ['Mind Over Munch', 'Pick Up Limes', 'Goodful'],
    },
    {
      category: 'Lifestyle & GRWM',
      engagement_pct: 68,
      description: 'Significant overlap with day-in-the-life, morning routine, and productivity content.',
      examples: ['AmandaRachLee', 'Rowena Tsai', 'Rachel Nguyen'],
    },
    {
      category: 'Sustainability & Eco Living',
      engagement_pct: 54,
      description: 'Growing affinity with zero-waste beauty, refillable packaging, and ethical brand discourse.',
      examples: ['Sustainably Vegan', 'Shelbizleee', 'Sustainably Lazy'],
    },
    {
      category: 'Dermatology & Science',
      engagement_pct: 61,
      description: 'Audience actively consumes evidence-based skincare education from medical professionals.',
      examples: ['Dr. Dray', 'Dr. Shereene Idriss', 'Dr. Sam Bunting'],
    },
    {
      category: 'Mental Wellbeing & Self-Care',
      engagement_pct: 48,
      description: 'Cross-appeal with self-care rituals, journaling, and mindfulness content communities.',
      examples: ['Lavendaire', 'Pick Up Limes', 'The Anna Edit'],
    },
  ],

  'Health & Wellness': [
    {
      category: 'Sports & Athletic Performance',
      engagement_pct: 82,
      description: 'Dominant overlap with strength training, endurance sports, and athletic coaching content.',
      examples: ['Jeff Nippard', 'AthleanX', 'Heria Pro'],
    },
    {
      category: 'Nutrition & Food Science',
      engagement_pct: 76,
      description: 'Strong audience crossover with meal planning, evidence-based dietary content, and food science.',
      examples: ['Ethan Chlebowski', 'Abbey Sharp', 'Layne Norton'],
    },
    {
      category: 'Sleep & Recovery',
      engagement_pct: 68,
      description: 'High engagement with sleep optimization, recovery science, and biohacking communities.',
      examples: ['Matthew Walker', 'Whoop', 'Levels Health'],
    },
    {
      category: 'Mental Health & Therapy',
      engagement_pct: 64,
      description: 'Significant crossover with mindfulness, cognitive behavioral content, and stress management.',
      examples: ['Therapy in a Nutshell', 'Dr. Tracey Marks', 'Kati Morton'],
    },
    {
      category: 'Supplements & Biohacking',
      engagement_pct: 72,
      description: 'Very high affinity with nootropics, longevity research, and performance optimization content.',
      examples: ['Dave Asprey', 'Rhonda Patrick', 'Siim Land'],
    },
    {
      category: 'Yoga & Mobility',
      engagement_pct: 58,
      description: 'Meaningful overlap with yoga, stretching, and functional movement communities.',
      examples: ['Yoga with Adriene', 'Tom Merrick', 'Patrick Beach'],
    },
  ],

  'Home & Living': [
    {
      category: 'Interior Design & Architecture',
      engagement_pct: 86,
      description: 'Primary affinity category — deep overlap with professional design, architecture tours, and renovation content.',
      examples: ['Architectural Digest', 'House Beautiful', 'Design Milk'],
    },
    {
      category: 'DIY & Home Improvement',
      engagement_pct: 74,
      description: 'Strong crossover with hands-on home renovation, woodworking, and crafting communities.',
      examples: ['Bob Vila', 'DIY Creators', 'Steve Ramsey'],
    },
    {
      category: 'Minimalism & Decluttering',
      engagement_pct: 68,
      description: 'High affinity with minimalist living, organisation systems, and intentional consumption.',
      examples: ['The Minimalists', 'Joshua Becker', 'Matt D\'Avella'],
    },
    {
      category: 'Real Estate & Property',
      engagement_pct: 58,
      description: 'Notable crossover with property investment, house tours, and real estate education.',
      examples: ['Graham Stephan', 'Meet Kevin', 'Kristina Smallhorn'],
    },
    {
      category: 'Sustainability & Eco Living',
      engagement_pct: 62,
      description: 'Significant interest in sustainable home products, energy efficiency, and conscious purchasing.',
      examples: ['Sustainably Lazy', 'Gittemary', 'Tolly T'],
    },
    {
      category: 'Luxury & Premium Goods',
      engagement_pct: 44,
      description: 'Cross-appeal with high-end product reviews, luxury furniture, and aspirational lifestyle content.',
      examples: ['Louis Fontaine', 'Luxe DuJour', 'Refinery29'],
    },
  ],

  'Food & Beverage': [
    {
      category: 'Restaurant & Dining Culture',
      engagement_pct: 84,
      description: 'Dominant crossover with restaurant reviews, chef profiles, and fine dining content.',
      examples: ['Eater', 'Bon Appétit', 'Munchies'],
    },
    {
      category: 'Health & Nutrition',
      engagement_pct: 76,
      description: 'Strong affinity with macro-counting, clean eating, and evidence-based nutrition communities.',
      examples: ['Abbey Sharp', 'Ethan Chlebowski', 'Layne Norton'],
    },
    {
      category: 'Travel & Food Culture',
      engagement_pct: 72,
      description: 'High overlap with food travel, street food exploration, and culinary cultural content.',
      examples: ['Mark Wiens', 'Luke Martin', 'Best Ever Food Review Show'],
    },
    {
      category: 'Cocktails & Spirits',
      engagement_pct: 58,
      description: 'Notable crossover with cocktail tutorials, wine education, and craft beverage culture.',
      examples: ['Cocktail Chemistry', 'Kara and Nate', 'Wine Folly'],
    },
    {
      category: 'Sustainability & Food Ethics',
      engagement_pct: 54,
      description: 'Growing affinity with plant-based eating, food waste reduction, and ethical sourcing content.',
      examples: ['Sustainably Vegan', 'Cheap Lazy Vegan', 'Derek Sarno'],
    },
    {
      category: 'Baking & Pastry',
      engagement_pct: 68,
      description: 'Significant overlap with baking tutorials, bread-making, and confectionery communities.',
      examples: ['Claire Saffitz', 'Preppy Kitchen', 'Binging with Babish'],
    },
  ],

  'Parenting & Family': [
    {
      category: 'Education & Child Development',
      engagement_pct: 84,
      description: 'Primary affinity — deep engagement with early learning, STEM for kids, and school readiness content.',
      examples: ['SciShow Kids', 'Crash Course Kids', 'TED-Ed'],
    },
    {
      category: 'Health & Paediatrics',
      engagement_pct: 74,
      description: 'Strong crossover with child nutrition, paediatric health, and family wellness content.',
      examples: ['Dr. Paul Thomas', 'Kids Cook Monday', 'Feeding Littles'],
    },
    {
      category: 'Home Organisation & Family Life',
      engagement_pct: 68,
      description: 'High affinity with household management, family routines, and home organisation systems.',
      examples: ['The Minimal Mom', 'A Bowl Full of Lemons', 'Clean Mama'],
    },
    {
      category: 'Toys & Children\'s Products',
      engagement_pct: 62,
      description: 'Notable overlap with toy review, unboxing, and children\'s product recommendation content.',
      examples: ['Ryan\'s World', 'HobbyKidsTV', 'FGTeeV'],
    },
    {
      category: 'Mindful & Gentle Parenting',
      engagement_pct: 58,
      description: 'Significant crossover with attachment parenting, emotional regulation, and conscious family content.',
      examples: ['Big Life Journal', 'Janet Lansbury', 'Occupational Therapy Toolkit'],
    },
    {
      category: 'Family Travel & Experiences',
      engagement_pct: 46,
      description: 'Cross-appeal with family travel vlogs, theme park guides, and vacation planning content.',
      examples: ['The Bucket List Family', 'FamilyOnTheRoad', 'Kara and Nate'],
    },
  ],
};

export const SENTIMENT_DATA = {
  'Beauty & Skincare': {
    sentiment: {
      score: 72,
      label: 'Positive',
      summary:
        'The Beauty & Skincare community maintains a strongly positive sentiment driven by shared enthusiasm for product discovery, routine-building, and educational content. Dominant discourse centres on ingredient science, shade inclusivity, and brand ethics. Clean beauty and sustainability messaging is gaining significant traction.',
    },
    keywords: [
      { keyword: 'skincare routine', mentions: 12840 },
      { keyword: 'SPF', mentions: 8420 },
      { keyword: 'retinol', mentions: 9640 },
      { keyword: 'glass skin', mentions: 7240 },
      { keyword: 'moisturiser', mentions: 11200 },
      { keyword: 'hyaluronic acid', mentions: 8840 },
      { keyword: 'vitamin C serum', mentions: 6480 },
      { keyword: 'clean beauty', mentions: 5240 },
      { keyword: 'shade range', mentions: 4820 },
      { keyword: 'cruelty-free', mentions: 4120 },
    ],
  },

  'Health & Wellness': {
    sentiment: {
      score: 82,
      label: 'Positive',
      summary:
        'Health & Wellness audiences demonstrate exceptionally high community sentiment, driven by aspirational goal-setting and peer encouragement. Discourse is substantive and science-forward, with strong engagement around longevity research, supplementation stacks, and biohacking protocols. Huberman-style educational long-form is the dominant format preference.',
    },
    keywords: [
      { keyword: 'intermittent fasting', mentions: 18400 },
      { keyword: 'sleep quality', mentions: 14200 },
      { keyword: 'cortisol', mentions: 9840 },
      { keyword: 'cold plunge', mentions: 12400 },
      { keyword: 'supplements', mentions: 16800 },
      { keyword: 'VO2 max', mentions: 7240 },
      { keyword: 'zone 2 cardio', mentions: 8420 },
      { keyword: 'longevity', mentions: 11200 },
      { keyword: 'protein intake', mentions: 14800 },
      { keyword: 'circadian rhythm', mentions: 9240 },
    ],
  },

  'Home & Living': {
    sentiment: {
      score: 76,
      label: 'Positive',
      summary:
        'The Home & Living community shows consistently positive sentiment anchored in aspiration and shared project pride. Content around sustainable materials, multifunctional design, and budget makeovers generates the highest engagement. Some friction around overconsumption narratives, offset by strong minimalism and slow-living sub-communities.',
    },
    keywords: [
      { keyword: 'interior design', mentions: 14800 },
      { keyword: 'room makeover', mentions: 12400 },
      { keyword: 'decluttering', mentions: 9840 },
      { keyword: 'small space living', mentions: 8420 },
      { keyword: 'sustainable home', mentions: 6840 },
      { keyword: 'thrift decor', mentions: 7240 },
      { keyword: 'minimalism', mentions: 10200 },
      { keyword: 'home organisation', mentions: 11800 },
      { keyword: 'colour palette', mentions: 5840 },
      { keyword: 'biophilic design', mentions: 4240 },
    ],
  },

  'Food & Beverage': {
    sentiment: {
      score: 84,
      label: 'Positive',
      summary:
        'Food & Beverage audiences exhibit the highest brand affinity in the dataset, driven by creator trust and product integration authenticity. Communities rally around technique mastery, ingredient quality, and cultural food storytelling. Recipe recreation and restaurant copycat content drives the highest comment engagement.',
    },
    keywords: [
      { keyword: 'meal prep', mentions: 22400 },
      { keyword: 'sourdough', mentions: 16800 },
      { keyword: 'plant-based', mentions: 14200 },
      { keyword: 'restaurant review', mentions: 18400 },
      { keyword: 'fermentation', mentions: 9840 },
      { keyword: 'food science', mentions: 8420 },
      { keyword: 'budget meals', mentions: 12400 },
      { keyword: 'food vlog', mentions: 16200 },
      { keyword: 'umami', mentions: 7240 },
      { keyword: 'recipe test', mentions: 10800 },
    ],
  },

  'Parenting & Family': {
    sentiment: {
      score: 71,
      label: 'Positive',
      summary:
        'The Parenting & Family community shows strong positive sentiment grounded in shared experience and mutual support. Gentle parenting and evidence-based childcare content drives high engagement. Some polarisation around screen time debates and parenting philosophy differences, but community cohesion is high and brand trust is exceptional for family-safe product categories.',
    },
    keywords: [
      { keyword: 'gentle parenting', mentions: 14800 },
      { keyword: 'toddler activities', mentions: 12400 },
      { keyword: 'screen time', mentions: 9840 },
      { keyword: 'homeschooling', mentions: 8420 },
      { keyword: 'baby development', mentions: 11200 },
      { keyword: 'sleep training', mentions: 7240 },
      { keyword: 'school readiness', mentions: 6840 },
      { keyword: 'emotional regulation', mentions: 8840 },
      { keyword: 'sensory play', mentions: 5840 },
      { keyword: 'family routine', mentions: 10200 },
    ],
  },
};

export const INSIGHT_DATA = {
  'Beauty & Skincare': {
    title: 'Beauty Audiences Are the Highest-Converting Cohort for Prestige Skincare Brands',
    summary:
      'The Beauty & Skincare audience combines aspirational purchasing intent with exceptional brand loyalty, making it the most commercially mature of all tracked niches. With 78% cross-affinity with fashion and luxury goods, this segment commands premium CPMs and delivers measurable purchase conversion for both mass-market and prestige brands. Creator trust is the defining currency.',
    keyBehaviors: [
      'Purchase decisions are 74% influenced by creator recommendation — highest in the dataset',
      'Skincare routine content drives 2.3× more engagement than makeup tutorials',
      'Morning consumption pattern (7AM–9AM) aligns with personal care routine windows',
      'High repeat-view behavior: tutorials watched an average of 2.6 times per user',
      'Ingredient research behavior — 61% cross-reference product claims on Reddit and forums',
    ],
    marketingAngles: [
      'Ingredient-led messaging outperforms packaging-led creative 3.4:1 in this cohort',
      'Before-and-after content formats drive the highest save and share rates by a significant margin',
      'Mid-tier creator partnerships (250K–1.5M) deliver the strongest trust and conversion metrics',
      'Sunday evening campaign timing aligns with weekly skincare planning and purchase intent peaks',
      'Dermatologist-endorsed claims increase click-through rates by 2.8× versus lifestyle positioning',
    ],
    confidence: 'high',
  },

  'Health & Wellness': {
    title: 'Health & Wellness Cohorts Represent the Fastest-Growing Premium Supplement Market Segment',
    summary:
      'The Health & Wellness audience is the most science-forward and commercially sophisticated segment in the Empirika dataset. Average content session lengths exceeding 45 minutes signal exceptional brand exposure per view. This cohort has the highest willingness-to-pay for premium health products and the strongest conversion from creator-endorsed supplements, equipment, and digital services.',
    keyBehaviors: [
      'Longest average watch session in the dataset: 44.8 minutes per sitting',
      'Supplement stack research is the dominant purchase driver — 68% research 3+ brands before converting',
      'Cross-platform stack sharing: audience actively shares protocol lists on Reddit and Twitter',
      'Morning engagement peak (5AM–8AM) correlates with pre-workout and supplement consumption windows',
      'Subscription and continuity product conversion rates are 3.8× higher than one-time purchases',
    ],
    marketingAngles: [
      'Clinical study citations in ad creative increase trust scores by 2.4× for this evidence-driven audience',
      'Long-form sponsored segments (4–8 minutes) are accepted — and expected — by this cohort',
      'Subscription supplement models convert at 4.2× versus single-purchase for this demographic',
      'Partnership with 2–3 high-authority creators delivers compounding credibility effects',
      'Bundle and protocol positioning outperforms individual product features across all formats',
    ],
    confidence: 'high',
  },

  'Home & Living': {
    title: 'Home & Living Audiences Drive the Highest Offline Purchase Conversion of Any Tracked Niche',
    summary:
      'The Home & Living segment demonstrates exceptional offline purchase behavior — 84% of engaged viewers report making a product purchase within 30 days of a creator recommendation. This cohort is disproportionately female (72%), aged 28–44, with above-average household income. Aspirational content with accessible price points converts most effectively.',
    keyBehaviors: [
      'Highest offline purchase conversion in the dataset: 84% within 30 days of creator mention',
      'Project-based browsing cycles — engagement spikes in 2–3 week bursts around home projects',
      'Pinterest cross-platform behavior: 78% of this audience also active on Pinterest',
      'Budget makeover content generates 2.8× the engagement of aspirational luxury content',
      'Brand recall is highest for products shown "in use" versus flat-lay product displays',
    ],
    marketingAngles: [
      'Room-specific creative outperforms generic home content — kitchen and bedroom perform best',
      'Before-and-after transformation formats drive the highest share and save rates',
      'Seasonal campaign alignment (January, May, September) tracks with home project planning cycles',
      'Mid-range price point products convert better than luxury — this audience wants aspirational but accessible',
      'Product placement in the background of "room tour" content generates sustained long-tail views',
    ],
    confidence: 'high',
  },

  'Food & Beverage': {
    title: 'Food & Beverage Creators Command the Strongest Brand Integration Authenticity Scores',
    summary:
      'The Food & Beverage niche is unique in that audiences actively expect and accept brand integration — provided the product fits the culinary narrative. This cohort shows the strongest purchase intent for kitchen equipment, premium ingredients, and meal kit subscriptions. Average watch completion rates are 42% above platform baseline due to the tutorial format dependency.',
    keyBehaviors: [
      'Watch completion rate 42% above platform average — audiences follow through to the end of tutorials',
      'Comment sections drive secondary discovery: 58% of viewers click on ingredient links from comments',
      'Recipe recreation behavior: 64% of engaged viewers attempt creator recipes within one week',
      'Grocery shopping pattern crossover: engagement peaks Sunday evening (meal planning window)',
      'High repeat-view behavior: technique videos watched 3.2 times on average per user',
    ],
    marketingAngles: [
      'Kitchen equipment and tool sponsorships deliver the highest authentic integration scores',
      'Ingredient sponsors perform best when shown "in process" — not as isolated product shots',
      'Meal kit and delivery service subscriptions convert at 3.4× versus standard food products',
      'Sunday evening campaign timing targets the peak meal planning and grocery consideration window',
      'User-generated recipe content from creator challenges drives the highest earned media amplification',
    ],
    confidence: 'high',
  },

  'Parenting & Family': {
    title: 'Parenting Audiences Are the Most Brand-Loyal Segment Across All Consumer Categories',
    summary:
      'The Parenting & Family cohort exhibits the highest long-term brand loyalty in the dataset — once trust is established, purchasing patterns remain consistent for 18+ months. This segment commands premium positioning for family-safe product categories, educational tools, and childhood nutrition. Mark Rober-style STEM entertainment commands the highest cross-generational engagement.',
    keyBehaviors: [
      'Highest long-term brand loyalty in dataset — 18-month average purchase relationship post-discovery',
      'Joint viewing behavior: 68% of content is watched by parent and child together, doubling exposure',
      'Safety and ingredient transparency are the primary brand evaluation criteria (89% of decisions)',
      'Weekend engagement dominates (Saturday 10AM–12PM peak) aligned with family activity windows',
      'Gift occasion concentration: 40% of purchase conversions cluster around Christmas, Easter, and birthdays',
    ],
    marketingAngles: [
      'Safety certification and transparency messaging is non-negotiable — lead with it in every creative',
      'Educational value positioning outperforms entertainment value for parenting audience conversion',
      'Gift set and occasion bundle products are the highest-converting format for this demographic',
      'Dual-audience creative (parent and child resonance simultaneously) commands premium engagement',
      'YouTube Kids and family creator alignment enables brand-safe placement at scale',
    ],
    confidence: 'high',
  },
};
