/**
 * Empirika Demo Data
 * Rich, realistic fake data powering the dashboard in demo mode.
 */

export const AUDIENCE_DATA = {
  Trades: [
    {
      channel_id: 'trd1',
      channel_name: "Mike's Electrical Mastery",
      subscriber_count: 1240000,
      total_views: 8430000,
      total_watch_hours: 421500,
      avg_view_duration_seconds: 723,
      total_subscribers_gained: 28400,
      total_likes: 312000,
      total_comments: 48200,
      trend: [44, 52, 49, 61, 58, 72, 80],
      trend_pct: +14.2,
    },
    {
      channel_id: 'trd2',
      channel_name: 'Pro Plumber Academy',
      subscriber_count: 892000,
      total_views: 5120000,
      total_watch_hours: 281000,
      avg_view_duration_seconds: 895,
      total_subscribers_gained: 18700,
      total_likes: 198000,
      total_comments: 31400,
      trend: [62, 58, 55, 60, 67, 63, 71],
      trend_pct: +8.7,
    },
    {
      channel_id: 'trd3',
      channel_name: 'HVAC Training Solutions',
      subscriber_count: 2100000,
      total_views: 12800000,
      total_watch_hours: 640000,
      avg_view_duration_seconds: 612,
      total_subscribers_gained: 41200,
      total_likes: 487000,
      total_comments: 72100,
      trend: [70, 74, 68, 75, 79, 84, 88],
      trend_pct: +22.1,
    },
    {
      channel_id: 'trd4',
      channel_name: 'Skilled Trades Network',
      subscriber_count: 567000,
      total_views: 3240000,
      total_watch_hours: 162000,
      avg_view_duration_seconds: 548,
      total_subscribers_gained: 11200,
      total_likes: 121000,
      total_comments: 19800,
      trend: [50, 46, 48, 44, 47, 50, 49],
      trend_pct: -2.4,
    },
    {
      channel_id: 'trd5',
      channel_name: 'Welding & Fabrication Pro',
      subscriber_count: 1580000,
      total_views: 9710000,
      total_watch_hours: 485500,
      avg_view_duration_seconds: 741,
      total_subscribers_gained: 32800,
      total_likes: 362000,
      total_comments: 56400,
      trend: [58, 62, 60, 68, 72, 76, 81],
      trend_pct: +17.8,
    },
  ],

  Mythology: [
    {
      channel_id: 'myt1',
      channel_name: 'Mythology & Folklore',
      subscriber_count: 2840000,
      total_views: 18200000,
      total_watch_hours: 910000,
      avg_view_duration_seconds: 1124,
      total_subscribers_gained: 64200,
      total_likes: 782000,
      total_comments: 142000,
      trend: [72, 78, 80, 84, 82, 88, 91],
      trend_pct: +26.4,
    },
    {
      channel_id: 'myt2',
      channel_name: 'Nordic Sagas',
      subscriber_count: 980000,
      total_views: 6240000,
      total_watch_hours: 312000,
      avg_view_duration_seconds: 987,
      total_subscribers_gained: 22100,
      total_likes: 289000,
      total_comments: 58400,
      trend: [54, 58, 62, 60, 65, 68, 72],
      trend_pct: +11.3,
    },
    {
      channel_id: 'myt3',
      channel_name: 'Greek & Roman Histories',
      subscriber_count: 1720000,
      total_views: 10800000,
      total_watch_hours: 540000,
      avg_view_duration_seconds: 1312,
      total_subscribers_gained: 38900,
      total_likes: 421000,
      total_comments: 94200,
      trend: [66, 70, 68, 74, 78, 76, 82],
      trend_pct: +18.9,
    },
    {
      channel_id: 'myt4',
      channel_name: 'Ancient Mythology Network',
      subscriber_count: 620000,
      total_views: 3840000,
      total_watch_hours: 192000,
      avg_view_duration_seconds: 876,
      total_subscribers_gained: 14800,
      total_likes: 168000,
      total_comments: 34100,
      trend: [48, 50, 52, 49, 54, 56, 58],
      trend_pct: +6.1,
    },
  ],

  Scouts: [
    {
      channel_id: 'sco1',
      channel_name: 'Wilderness Scouts',
      subscriber_count: 720000,
      total_views: 4120000,
      total_watch_hours: 206000,
      avg_view_duration_seconds: 843,
      total_subscribers_gained: 16400,
      total_likes: 182000,
      total_comments: 28700,
      trend: [52, 56, 54, 60, 58, 64, 68],
      trend_pct: +9.4,
    },
    {
      channel_id: 'sco2',
      channel_name: 'Outdoor Skills Academy',
      subscriber_count: 1340000,
      total_views: 7800000,
      total_watch_hours: 390000,
      avg_view_duration_seconds: 927,
      total_subscribers_gained: 29800,
      total_likes: 324000,
      total_comments: 52100,
      trend: [64, 68, 66, 72, 76, 80, 84],
      trend_pct: +19.6,
    },
    {
      channel_id: 'sco3',
      channel_name: 'Survival Readiness',
      subscriber_count: 890000,
      total_views: 5240000,
      total_watch_hours: 262000,
      avg_view_duration_seconds: 718,
      total_subscribers_gained: 19200,
      total_likes: 218000,
      total_comments: 38400,
      trend: [58, 54, 56, 60, 58, 62, 64],
      trend_pct: +5.8,
    },
    {
      channel_id: 'sco4',
      channel_name: 'Camping & Exploration',
      subscriber_count: 460000,
      total_views: 2640000,
      total_watch_hours: 132000,
      avg_view_duration_seconds: 634,
      total_subscribers_gained: 9800,
      total_likes: 112000,
      total_comments: 18200,
      trend: [44, 48, 46, 44, 50, 48, 46],
      trend_pct: -1.8,
    },
  ],

  Neurodivergent: [
    {
      channel_id: 'neu1',
      channel_name: 'How to ADHD',
      subscriber_count: 1860000,
      total_views: 11200000,
      total_watch_hours: 560000,
      avg_view_duration_seconds: 892,
      total_subscribers_gained: 42100,
      total_likes: 498000,
      total_comments: 124000,
      trend: [68, 72, 76, 74, 80, 84, 88],
      trend_pct: +23.7,
    },
    {
      channel_id: 'neu2',
      channel_name: 'Autism From the Inside',
      subscriber_count: 780000,
      total_views: 4680000,
      total_watch_hours: 234000,
      avg_view_duration_seconds: 1124,
      total_subscribers_gained: 18200,
      total_likes: 214000,
      total_comments: 68400,
      trend: [54, 58, 60, 62, 64, 68, 70],
      trend_pct: +13.2,
    },
    {
      channel_id: 'neu3',
      channel_name: 'ADHD & Dyslexia Hub',
      subscriber_count: 540000,
      total_views: 3120000,
      total_watch_hours: 156000,
      avg_view_duration_seconds: 748,
      total_subscribers_gained: 12800,
      total_likes: 148000,
      total_comments: 42100,
      trend: [46, 50, 52, 54, 56, 58, 62],
      trend_pct: +10.4,
    },
    {
      channel_id: 'neu4',
      channel_name: 'Sensory Processing Lab',
      subscriber_count: 320000,
      total_views: 1840000,
      total_watch_hours: 92000,
      avg_view_duration_seconds: 984,
      total_subscribers_gained: 8400,
      total_likes: 92000,
      total_comments: 31200,
      trend: [38, 40, 42, 44, 42, 46, 48],
      trend_pct: +7.1,
    },
  ],

  Stories: [
    {
      channel_id: 'str1',
      channel_name: 'Bedtime Stories',
      subscriber_count: 3240000,
      total_views: 21400000,
      total_watch_hours: 1070000,
      avg_view_duration_seconds: 1542,
      total_subscribers_gained: 78400,
      total_likes: 928000,
      total_comments: 168000,
      trend: [78, 82, 86, 84, 90, 92, 96],
      trend_pct: +31.2,
    },
    {
      channel_id: 'str2',
      channel_name: 'Nexpo',
      subscriber_count: 1480000,
      total_views: 8920000,
      total_watch_hours: 446000,
      avg_view_duration_seconds: 2184,
      total_subscribers_gained: 36200,
      total_likes: 412000,
      total_comments: 94800,
      trend: [64, 68, 72, 70, 76, 80, 84],
      trend_pct: +20.8,
    },
    {
      channel_id: 'str3',
      channel_name: 'True Crime Stories',
      subscriber_count: 2180000,
      total_views: 13800000,
      total_watch_hours: 690000,
      avg_view_duration_seconds: 1876,
      total_subscribers_gained: 52400,
      total_likes: 624000,
      total_comments: 142000,
      trend: [72, 74, 70, 76, 78, 82, 86],
      trend_pct: +17.4,
    },
    {
      channel_id: 'str4',
      channel_name: 'Narrative Collective',
      subscriber_count: 640000,
      total_views: 3840000,
      total_watch_hours: 192000,
      avg_view_duration_seconds: 1284,
      total_subscribers_gained: 14800,
      total_likes: 172000,
      total_comments: 38200,
      trend: [50, 54, 52, 56, 58, 60, 64],
      trend_pct: +12.1,
    },
  ],
};

export const TOTAL_TRENDS = {
  Trades:        { views: +18.4, watchHours: +16.2, avgDuration: +4.8, subscribers: +24.1 },
  Mythology:     { views: +28.6, watchHours: +26.4, avgDuration: +8.2, subscribers: +34.8 },
  Scouts:        { views: +14.2, watchHours: +12.8, avgDuration: +3.1, subscribers: +19.4 },
  Neurodivergent:{ views: +22.1, watchHours: +20.4, avgDuration: +6.7, subscribers: +28.6 },
  Stories:       { views: +34.8, watchHours: +32.1, avgDuration: +11.4, subscribers: +42.2 },
};

export const AFFINITY_DATA = {
  Trades: [
    {
      category: 'Trucks & Automotive',
      engagement_pct: 72,
      description: 'High overlap with truck enthusiasts, automotive maintenance, and off-road adventure content.',
      examples: ['Diesel Creek', 'WhistlinDiesel', 'Truck Central'],
    },
    {
      category: 'DIY Home Improvement',
      engagement_pct: 68,
      description: 'Audience actively engages with home renovation, tool tutorials, and project walkthroughs.',
      examples: ['This Old House', 'DIY Creators', 'Steve Ramsey'],
    },
    {
      category: 'Entrepreneurship & Business',
      engagement_pct: 58,
      description: 'Strong overlap with self-employment content — running a trade business, pricing, client management.',
      examples: ['Alex Hormozi', 'BIAHEZA', 'Graham Stephan'],
    },
    {
      category: 'Fitness & Physical Wellness',
      engagement_pct: 44,
      description: 'Blue-collar audience values physical strength and wellness content aligned with active lifestyles.',
      examples: ['Alan Thrall', 'Starting Strength', 'Bart Kay'],
    },
    {
      category: 'Finance & Wealth Building',
      engagement_pct: 41,
      description: 'Interest in financial independence, investment strategies, and wealth-building beyond trade income.',
      examples: ['Dave Ramsey', 'Financial Tortoise', 'Caleb Hammer'],
    },
    {
      category: 'Hunting & Outdoors',
      engagement_pct: 38,
      description: 'Significant crossover with hunting, fishing, and outdoor recreation communities.',
      examples: ['MeatEater', 'Rinella Outdoors', 'Born & Raised'],
    },
  ],

  Mythology: [
    {
      category: 'History & Ancient Civilizations',
      engagement_pct: 84,
      description: 'Deep interest in ancient history, archaeology, and the study of past civilizations.',
      examples: ['Toldinstone', 'Historia Civilis', 'Fall of Civilizations'],
    },
    {
      category: 'Literature & Storytelling',
      engagement_pct: 76,
      description: 'Audience actively seeks literary analysis, epic storytelling, and narrative craft content.',
      examples: ['Like Stories of Old', 'Jack Edwards', 'Merphy Napier'],
    },
    {
      category: 'Fantasy & Worldbuilding',
      engagement_pct: 71,
      description: 'Strong overlap with TTRPG, fantasy fiction, and creative worldbuilding communities.',
      examples: ["Overly Sarcastic Productions", "Terrible Writing Advice", "Quinn's Ideas"],
    },
    {
      category: 'Philosophy & Ethics',
      engagement_pct: 61,
      description: 'Audience engages with philosophy, stoicism, and ethical frameworks drawn from ancient thought.',
      examples: ['Academy of Ideas', 'Philosophize This!', 'Einzelgänger'],
    },
    {
      category: 'Gaming (RPG & Strategy)',
      engagement_pct: 54,
      description: 'Significant crossover with role-playing and strategy games with historical/mythological settings.',
      examples: ['Total War', 'Mandalore Gaming', 'Hades Reviews'],
    },
    {
      category: 'Science & Cosmology',
      engagement_pct: 47,
      description: 'Cross-appeal with cosmic mythology — quantum mechanics, universe origins, and scientific wonder.',
      examples: ['PBS Space Time', 'Kurzgesagt', 'SciShow'],
    },
  ],

  Scouts: [
    {
      category: 'Survival & Bushcraft',
      engagement_pct: 88,
      description: 'Highest affinity category — deep overlap with primitive survival skills and wilderness living.',
      examples: ['Primitive Technology', 'My Self Reliance', 'Coalcracker Bushcraft'],
    },
    {
      category: 'Geography & Exploration',
      engagement_pct: 79,
      description: 'Keen interest in cartography, geography education, and exploration narratives.',
      examples: ['RealLifeLore', 'Wendover Productions', 'Extremities'],
    },
    {
      category: 'Homesteading & Self-Sufficiency',
      engagement_pct: 64,
      description: 'Significant overlap with off-grid living, food growing, and sustainable homesteading.',
      examples: ['Justin Rhodes', 'Roots & Refuge', 'Pure Living for Life'],
    },
    {
      category: 'Firearms & Self-Defense',
      engagement_pct: 52,
      description: 'Notable crossover with firearms safety, preparedness, and self-reliance communities.',
      examples: ['Paul Harrell', 'Garand Thumb', 'Lucky Gunner'],
    },
    {
      category: 'Youth Leadership & Parenting',
      engagement_pct: 43,
      description: 'Crossover with content about raising resilient children and structured youth development.',
      examples: ['The Art of Manliness', 'Dad Advice', 'Jordan B Peterson'],
    },
    {
      category: 'Camping & Hiking',
      engagement_pct: 71,
      description: 'Strong engagement with gear reviews, trip planning, and trail documentation.',
      examples: ['Kraig Adams', 'Darwin on the Trail', 'Andrew Skurka'],
    },
  ],

  Neurodivergent: [
    {
      category: 'Mental Health & Therapy',
      engagement_pct: 82,
      description: 'High engagement with CBT content, therapy journeys, mental health advocacy and self-advocacy.',
      examples: ['Kati Morton', 'Dr. Tracey Marks', 'Therapy in a Nutshell'],
    },
    {
      category: 'Productivity & Life Organization',
      engagement_pct: 74,
      description: 'Deep interest in systems, frameworks, and tools adapted to non-linear thinking styles.',
      examples: ['Thomas Frank', 'Ali Abdaal', 'ADHD Rewired'],
    },
    {
      category: 'Science & Research Communication',
      engagement_pct: 68,
      description: 'Significant overlap with scientific content — especially neuroscience and behavioral science.',
      examples: ['Andrew Huberman', 'Dr. K', 'SciShow Psych'],
    },
    {
      category: 'Gaming (Indie & Strategy)',
      engagement_pct: 61,
      description: 'Strong crossover with gaming communities that value deep systems, storytelling, and immersion.',
      examples: ["Game Maker's Toolkit", 'Dunkey', 'Mark Brown'],
    },
    {
      category: 'Art & Creative Expression',
      engagement_pct: 55,
      description: 'Engagement with process-focused art content, illustration, and creative flow states.',
      examples: ['Struthless', 'Kasey Golden', 'JazzaStudios'],
    },
    {
      category: 'Advocacy & Social Change',
      engagement_pct: 49,
      description: 'Audience actively consumes disability rights, neurodiversity advocacy, and systemic critique.',
      examples: ['Imani Barbarin', 'Neurodivergent Rebel', 'Kat Blaque'],
    },
  ],

  Stories: [
    {
      category: 'True Crime & Investigation',
      engagement_pct: 81,
      description: 'Dominant crossover with true crime podcast audiences and investigative journalism communities.',
      examples: ['Stephanie Harlowe', 'Crime Weekly', 'Criminally Listed'],
    },
    {
      category: 'Documentary & Journalism',
      engagement_pct: 72,
      description: 'Strong engagement with long-form investigative content, documentary-style reporting.',
      examples: ['Vice', 'Coffeezilla', 'Nick Crowley'],
    },
    {
      category: 'Psychology & Human Behavior',
      engagement_pct: 66,
      description: 'High engagement with content exploring psychological profiles, criminal minds, and social dynamics.',
      examples: ['Dr. Ramani', 'Patrick Teahan', 'Surviving Narcissism'],
    },
    {
      category: 'Horror & Paranormal',
      engagement_pct: 64,
      description: 'Significant overlap with horror fiction, supernatural storytelling, and creepypasta communities.',
      examples: ['Night Mind', 'Corpse Husband', 'The Dead Meat Podcast'],
    },
    {
      category: 'Books & Literary Analysis',
      engagement_pct: 58,
      description: 'Notable affinity with Booktok communities, literary criticism, and author-focused content.',
      examples: ['Daniel Greene', 'Merphy Napier', 'Sage Polaris'],
    },
    {
      category: 'Animation & Visual Storytelling',
      engagement_pct: 47,
      description: 'Crossover with animated essay format consumers and visual narrative enthusiasts.',
      examples: ['Kurzgesagt', 'Nerdwriter1', 'Like Stories of Old'],
    },
  ],
};

export const SENTIMENT_DATA = {
  Trades: {
    sentiment: {
      score: 78,
      label: 'Positive',
      summary:
        'The Trades audience maintains a highly positive community sentiment driven by pride in craftsmanship, peer recognition, and practical skill-sharing. Dominant themes include mentorship, the value of skilled trades as career paths, and anti-credential discourse.',
    },
    keywords: [
      { keyword: 'tools', mentions: 5920 },
      { keyword: 'electrician', mentions: 4120 },
      { keyword: 'trade school', mentions: 3140 },
      { keyword: 'skilled trades', mentions: 3680 },
      { keyword: 'apprenticeship', mentions: 2840 },
      { keyword: 'journeyman', mentions: 2210 },
      { keyword: 'HVAC technician', mentions: 2710 },
      { keyword: 'no degree needed', mentions: 1820 },
      { keyword: 'union benefits', mentions: 1480 },
      { keyword: 'plumbing career', mentions: 1940 },
    ],
  },

  Mythology: {
    sentiment: {
      score: 84,
      label: 'Positive',
      summary:
        'Mythology audiences demonstrate exceptional community positivity, driven by intellectual curiosity and shared wonder. Discourse is substantive and collegial, with high engagement around interpretive debates, adaptations, and cross-cultural mythological comparisons.',
    },
    keywords: [
      { keyword: 'Norse mythology', mentions: 6240 },
      { keyword: 'folklore', mentions: 5640 },
      { keyword: 'Greek gods', mentions: 8120 },
      { keyword: 'hero\'s journey', mentions: 4120 },
      { keyword: 'ancient religions', mentions: 3480 },
      { keyword: 'Ragnarök', mentions: 2840 },
      { keyword: 'Olympians', mentions: 3920 },
      { keyword: 'Celtic lore', mentions: 2140 },
      { keyword: 'pantheons', mentions: 1940 },
      { keyword: 'mythology podcast', mentions: 1680 },
    ],
  },

  Scouts: {
    sentiment: {
      score: 71,
      label: 'Positive',
      summary:
        'The Scouts and Outdoor community shows strong positive sentiment anchored in shared experiences and practical skills. Discourse centers on gear recommendations, safety practices, and the value of outdoor youth programs. Some friction around commercialization of nature content.',
    },
    keywords: [
      { keyword: 'camping gear', mentions: 6840 },
      { keyword: 'fire starting', mentions: 4920 },
      { keyword: 'survival tips', mentions: 5120 },
      { keyword: 'bushcraft skills', mentions: 3840 },
      { keyword: 'shelter building', mentions: 3240 },
      { keyword: 'scouting traditions', mentions: 2140 },
      { keyword: 'outdoor leadership', mentions: 2180 },
      { keyword: 'knot tying', mentions: 2840 },
      { keyword: 'wilderness first aid', mentions: 1680 },
      { keyword: 'merit badges', mentions: 1420 },
    ],
  },

  Neurodivergent: {
    sentiment: {
      score: 69,
      label: 'Positive',
      summary:
        'The Neurodivergent community shows moderately positive sentiment with high emotional depth. Dominant themes include self-advocacy, late diagnosis experiences, and mutual support. Some negative sentiment around systemic failures in education and healthcare access. Community cohesion is exceptional.',
    },
    keywords: [
      { keyword: 'neurodiversity', mentions: 8240 },
      { keyword: 'ADHD diagnosis', mentions: 7840 },
      { keyword: 'autism spectrum', mentions: 6120 },
      { keyword: 'hyperfocus', mentions: 5640 },
      { keyword: 'late diagnosis', mentions: 4920 },
      { keyword: 'masking', mentions: 4180 },
      { keyword: 'executive function', mentions: 3480 },
      { keyword: 'sensory overload', mentions: 3240 },
      { keyword: 'AuDHD', mentions: 2840 },
      { keyword: 'stimming', mentions: 3120 },
    ],
  },

  Stories: {
    sentiment: {
      score: 73,
      label: 'Positive',
      summary:
        'The Stories audience shows strong positive engagement driven by the communal experience of narrative consumption. True crime sub-segments show heightened emotional engagement. Communities value meticulous research, empathetic framing, and high production quality above all else.',
    },
    keywords: [
      { keyword: 'true crime podcast', mentions: 9240 },
      { keyword: 'deep dive', mentions: 8120 },
      { keyword: 'unsolved mysteries', mentions: 6480 },
      { keyword: 'mystery solved', mentions: 4920 },
      { keyword: 'storytelling format', mentions: 4120 },
      { keyword: 'victim advocacy', mentions: 3480 },
      { keyword: 'case files', mentions: 3680 },
      { keyword: 'documentary style', mentions: 2940 },
      { keyword: 'investigative journalism', mentions: 3240 },
      { keyword: 'narrative essay', mentions: 2840 },
    ],
  },
};

export const INSIGHT_DATA = {
  Trades: {
    title: 'Trades Audiences Are Primed for High-Ticket Career Tools',
    summary:
      'The Trades audience represents a high-intent, underserved commercial segment. With median engagement durations exceeding 12 minutes and a 78% positive sentiment index, this cohort demonstrates a rare combination of brand loyalty and purchasing power. Career advancement tools, premium equipment brands, and entrepreneurship courses represent the highest-conversion opportunity categories.',
    keyBehaviors: [
      'Watch completion rates 34% above platform average, indicating deep content investment',
      'Comment sentiment skews toward skill-sharing and mentorship requests (62% of thread discourse)',
      'Weekend engagement spikes correlate with project preparation cycles (Friday–Saturday)',
      'High brand recall for tool manufacturers mentioned in instructional contexts',
      'Cross-platform migration to Reddit and trade forums for peer validation of purchasing decisions',
    ],
    marketingAngles: [
      'Position products as professional-grade tools that serious tradespeople rely on',
      'Leverage apprenticeship and mentorship narratives — this audience responds to legacy and craft pride',
      'Partner with mid-tier creators (200K–800K) for highest efficiency and audience trust',
      'Saturday morning campaigns align with peak project-planning engagement windows',
      'Certification and career advancement angles outperform lifestyle messaging 3:1',
    ],
    confidence: 'high',
  },

  Mythology: {
    title: 'Mythology Cohorts Are the Most Educationally Receptive Segment in the Dataset',
    summary:
      'With a sentiment score of 84 — the highest across all tracked niches — the Mythology audience represents an exceptionally intelligent, curious, and commercially engaged segment. Average watch duration exceeding 19 minutes signals premium content tolerance. This cohort responds strongly to intellectual positioning and long-form storytelling from brand partners.',
    keyBehaviors: [
      'Highest average comment length in the dataset (87 words), indicating intellectual engagement depth',
      'Strong cross-platform behavior: 71% also active on Reddit mythology communities and Discord servers',
      'Subscription rates to educational platforms (MasterClass, Curiosity Stream) 4.2× platform average',
      'Book purchase conversion from creator recommendations among the highest in entertainment niches',
      'Seasonal engagement spikes around solstices, Norse/Greek calendar events, and fantasy release windows',
    ],
    marketingAngles: [
      'Educational and cultural positioning performs far above direct-response for this segment',
      'Podcast sponsorship converts at 2.8× YouTube pre-roll due to trust dynamics in this niche',
      'Books, courses, and documentary streaming services are the natural commercial fit',
      'Avoid mass-market product placement — this audience penalizes perceived inauthenticity sharply',
      'Long-form sponsored segments (90+ seconds) outperform standard 30-second integrations by 2.1×',
    ],
    confidence: 'high',
  },

  Scouts: {
    title: 'Scouts Audience Holds Exceptional Brand Loyalty for Gear and Preparedness Brands',
    summary:
      'The Outdoor and Scouts cohort demonstrates the highest purchase intent signals for physical goods of any tracked niche. Gear reviews drive measurable conversion events, with affiliate click-through rates averaging 8.4% versus the 2.1% platform benchmark. This audience rewards authenticity and penalizes obvious commercialism.',
    keyBehaviors: [
      'Gear-review videos generate 2.8× the standard engagement rate of general outdoor content',
      'Audience skews toward 28–45 male demographic with confirmed household income above $75K',
      'High multi-platform behavior: YouTube for education, Reddit for community validation, Amazon for conversion',
      'Long-term content relationships: average subscription tenure of 14 months before first purchase conversion',
      'Preparedness and emergency readiness sub-segments showing 40% year-over-year engagement growth',
    ],
    marketingAngles: [
      'Gear and equipment sponsors see 3.4× ROI versus entertainment brands in this space',
      'Authenticity signals are critical — use creators who actually use the product in their content',
      'Family preparedness angles expand the addressable audience to household decision-makers',
      'Seasonal campaign windows: spring (gear-up) and autumn (hunting/camping prep) peak seasons',
      'Subscription boxes and membership programs have strong recurring revenue fit for this cohort',
    ],
    confidence: 'high',
  },

  Neurodivergent: {
    title: 'Neurodivergent Audiences Demand Systemic Trust Before Commercial Engagement',
    summary:
      'The Neurodivergent community is highly sophisticated, with above-average media literacy and strong collective skepticism toward commercial messaging. However, brands that engage authentically — especially those demonstrating genuine understanding of neurodivergent needs — see extraordinary loyalty metrics. This is a community that advocates loudly for brands it trusts.',
    keyBehaviors: [
      'Highest channel loyalty scores in dataset — average subscription tenure of 22 months',
      'Comment discourse is the most emotionally nuanced, with high rates of peer support exchange',
      'Strong advocacy behavior: 3.8× more likely than average to recommend products in community spaces',
      'Significant backlash to neurotypical-coded messaging — brand failures spread rapidly here',
      'Afternoon engagement peak (2PM–5PM) correlates with ADHD executive function windows',
    ],
    marketingAngles: [
      'Accommodate cognitive diversity in ad creative — clear messaging, no sensory overwhelm',
      'Tools for focus, organization, and self-management are the highest-converting category',
      'Community sponsorship (Discord, Patreon support) outperforms traditional ad placements',
      'Creator-read endorsements convert at 4.1× pre-roll for this highly creator-loyal audience',
      'Representation matters: feature neurodivergent talent in brand creative when possible',
    ],
    confidence: 'medium',
  },

  Stories: {
    title: 'Stories Audience Is the Highest-Value Segment for Premium Subscription Brands',
    summary:
      'The Stories niche commands the longest average view durations in the entire Empirika dataset — nearly 32 minutes per video session. This cohort is optimized for subscription product conversion, with audio streaming, true crime podcasts, and premium journalism platforms all demonstrating strong brand fit. Community trust is paramount.',
    keyBehaviors: [
      'Longest average session duration across all tracked niches: 31.8 minutes per sitting',
      'High true crime podcast crossover: 68% of audience consumes 3+ podcasts per week',
      'Strong Patreon conversion rates — creator monetization success highest in this niche',
      'Evening engagement dominance (8PM–11PM) aligns with wind-down, high-attention viewing patterns',
      'Social sharing rates 2.4× platform average — this audience actively curates and shares',
    ],
    marketingAngles: [
      'Subscription streaming services (Audible, Spotify, Curiosity Stream) are natural brand partners',
      'True crime adjacent product categories (home security, VPN, self-defense) convert strongly',
      'Evening-timed campaigns align with peak engagement and purchase decision windows',
      'Long-form mid-roll placements outperform pre-roll by 3.2× in this high-attention niche',
      'Community-first campaigns (exclusive content, early access) drive exceptional lifetime value',
    ],
    confidence: 'high',
  },
};
